CHOICES_CITIES = (
    ("Aleksandrów Kujawski", "Aleksandrów Kujawski"),
    ("Andrychów", "Andrychów"),
    ("Aleksandrów Łódzki", "Aleksandrów Łódzki"),
    ("Annopol", "Annopol"),
    ("Alwernia", "Alwernia"),
    ("Augustów", "Augustów"),
    ("Babimost", "Babimost"),
    ("Barczewo", "Barczewo"),
    ("Barwice", "Barwice"),
    ("Baborów", "Baborów"),
    ("Bardo", "Bardo"),
    ("Bełchatów", "Bełchatów"),
    ("Baranów Sandomierski", "Baranów Sandomierski"),
    ("Barlinek", "Barlinek"),
    ("Bełżyce", "Bełżyce"),
    ("Barcin", "Barcin"),
    ("Bartoszyce", "Bartoszyce"),
    ("Będzin", "Będzin"),
    ("Biała", "Biała"),
    ("Biecz", "Biecz"),
    ("Bieżuń", "Bieżuń"),
    ("Biała Piska", "Biała Piska"),
    ("Bielawa", "Bielawa"),
    ("Biłgoraj", "Biłgoraj"),
    ("Biała Podlaska", "Biała Podlaska"),
    ("Bielsk Podlaski", "Bielsk Podlaski"),
    ("Biskupiec", "Biskupiec"),
    ("Biała Rawska", "Biała Rawska"),
    ("Bielsko-Biała", "Bielsko-Biała"),
    ("Bisztynek", "Bisztynek"),
    ("Białobrzegi", "Białobrzegi"),
    ("Bieruń", "Bieruń"),
    ("Blachownia", "Blachownia"),
    ("Białogard", "Białogard"),
    ("Bierutów", "Bierutów"),
    ("Błaszki", "Błaszki"),
    ("Biały Bór", "Biały Bór"),
    ("Błażowa", "Błażowa"),
    ("Białystok", "Białystok"),
    ("Błonie", "Błonie"),
    ("Bobolice", "Bobolice"),
    ("Bolków", "Bolków"),
    ("Brzeg", "Brzeg"),
    ("Bobowa", "Bobowa"),
    ("Borek Wielkopolski", "Borek Wielkopolski"),
    ("Brzeg Dolny", "Brzeg Dolny"),
    ("Bochnia", "Bochnia"),
    ("Borne Sulinowo", "Borne Sulinowo"),
    ("Brzesko", "Brzesko"),
    ("Bodzentyn", "Bodzentyn"),
    ("Braniewo", "Braniewo"),
    ("Brzeszcze", "Brzeszcze"),
    ("Bogatynia", "Bogatynia"),
    ("Brańsk", "Brańsk"),
    ("Brześć Kujawski", "Brześć Kujawski"),
    ("Boguchwała", "Boguchwała"),
    ("Brodnica", "Brodnica"),
    ("Brzeziny", "Brzeziny"),
    ("Boguszów-Gorce", "Boguszów-Gorce"),
    ("Brok", "Brok"),
    ("Brzostek", "Brzostek"),
    ("Bojanowo", "Bojanowo"),
    ("Brusy", "Brusy"),
    ("Brzozów", "Brzozów"),
    ("Bolesławiec", "Bolesławiec"),
    ("Brwinów", "Brwinów"),
    ("Buk", "Buk"),
    ("Bydgoszcz", "Bydgoszcz"),
    ("Bukowno", "Bukowno"),
    ("Bystrzyca Kłodzka", "Bystrzyca Kłodzka"),
    ("Busko Zdrój", "Busko Zdrój"),
    ("Bytom", "Bytom"),
    ("Bychawa", "Bychawa"),
    ("Bytom Odrzański", "Bytom Odrzański"),
    ("Byczyna", "Byczyna"),
    ("Bytów", "Bytów"),
    ("Cedynia", "Cedynia"),
    ("Chocianów", "Chocianów"),
    ("Chojnów", "Chojnów"),
    ("Chełm", "Chełm"),
    ("Chociwel", "Chociwel"),
    ("Choroszcz", "Choroszcz"),
    ("Chełmek", "Chełmek"),
    ("Chocz", "Chocz"),
    ("Chorzele", "Chorzele"),
    ("Chełmno", "Chełmno"),
    ("Chodecz", "Chodecz"),
    ("Chorzów", "Chorzów"),
    ("Chełmża", "Chełmża"),
    ("Chodzież", "Chodzież"),
    ("Choszczno", "Choszczno"),
    ("Chęciny", "Chęciny"),
    ("Chojna", "Chojna"),
    ("Chrzanów", "Chrzanów"),
    ("Chmielnik", "Chmielnik"),
    ("Chojnice", "Chojnice"),
    ("Ciechanowiec", "Ciechanowiec"),
    ("Czarna Białostocka", "Czarna Białostocka"),
    ("Czerniejewo", "Czerniejewo"),
    ("Ciechanów", "Ciechanów"),
    ("Czarna Woda", "Czarna Woda"),
    ("Czersk", "Czersk"),
    ("Ciechocinek", "Ciechocinek"),
    ("Czarne", "Czarne"),
    ("Czerwieńsk", "Czerwieńsk"),
    ("Cieszanów", "Cieszanów"),
    ("Czarnków", "Czarnków"),
    ("Czerwionka-Leszczyny", "Czerwionka-Leszczyny"),
    ("Cieszyn", "Cieszyn"),
    ("Czchów", "Czchów"),
    ("Częstochowa", "Częstochowa"),
    ("Ciężkowice", "Ciężkowice"),
    ("Czechowice-Dziedzice", "Czechowice-Dziedzice"),
    ("Człopa", "Człopa"),
    ("Cybinka", "Cybinka"),
    ("Czeladź", "Czeladź"),
    ("Człuchów", "Człuchów"),
    ("Czaplinek", "Czaplinek"),
    ("Czempiń", "Czempiń"),
    ("Czyżew", "Czyżew"),
    ("Daleszyce", "Daleszyce"),
    ("Debrzno", "Debrzno"),
    ("Dobra (Turek County)", "Dobra (Turek County)"),
    ("Darłowo", "Darłowo"),
    ("Dębica", "Dębica"),
    ("Dobre Miasto", "Dobre Miasto"),
    ("Dąbie", "Dąbie"),
    ("Dęblin", "Dęblin"),
    ("Dobrodzień", "Dobrodzień"),
    ("Dąbrowa Białostocka", "Dąbrowa Białostocka"),
    ("Dębno", "Dębno"),
    ("Dobrzany", "Dobrzany"),
    ("Dąbrowa Górnicza", "Dąbrowa Górnicza"),
    ("Dobczyce", "Dobczyce"),
    ("Dobrzyca", "Dobrzyca"),
    ("Dąbrowa Tarnowska", "Dąbrowa Tarnowska"),
    ("Dobiegniew", "Dobiegniew"),
    ("Dobrzyń nad Wisłą", "Dobrzyń nad Wisłą"),
    ("Dąbrowa Tarnowska", "Dąbrowa Tarnowska"),
    ("Dobra (Łobez County)", "Dobra (Łobez County)"),
    ("Dolsk", "Dolsk"),
    ("Drawno", "Drawno"),
    ("Drzewica", "Drzewica"),
    ("Działoszyce", "Działoszyce"),
    ("Drawsko Pomorskie", "Drawsko Pomorskie"),
    ("Dukla", "Dukla"),
    ("Działoszyn", "Działoszyn"),
    ("Drezdenko", "Drezdenko"),
    ("Duszniki Zdrój", "Duszniki Zdrój"),
    ("Dzierzgoń", "Dzierzgoń"),
    ("Drobin", "Drobin"),
    ("Dynów", "Dynów"),
    ("Dzierżoniów", "Dzierżoniów"),
    ("Drohiczyn", "Drohiczyn"),
    ("Działdowo", "Działdowo"),
    ("Dziwnów", "Dziwnów"),
    ("Elbląg", "Elbląg"),
    ("Ełk", "Ełk"),
    ("Frampol", "Frampol"),
    ("Frombork", "Frombork"),
    ("Garwolin", "Garwolin"),
    ("Gliwice", "Gliwice"),
    ("Głuchołazy", "Głuchołazy"),
    ("Gąbin", "Gąbin"),
    ("Głogów", "Głogów"),
    ("Głuszyca", "Głuszyca"),
    ("Gdańsk", "Gdańsk"),
    ("Głogów Małopolski", "Głogów Małopolski"),
    ("Gniew", "Gniew"),
    ("Gdynia", "Gdynia"),
    ("Głogówek", "Głogówek"),
    ("Gniewkowo", "Gniewkowo"),
    ("Giżycko", "Giżycko"),
    ("Głowno", "Głowno"),
    ("Gniezno", "Gniezno"),
    ("Glinojeck", "Glinojeck"),
    ("Głubczyce", "Głubczyce"),
    ("Gniewkowo", "Gniewkowo"),
    ("Gogolin", "Gogolin"),
    ("Goniądz", "Goniądz"),
    ("Gostyń", "Gostyń"),
    ("Golczewo", "Golczewo"),
    ("Gorlice", "Gorlice"),
    ("Gozdnica", "Gozdnica"),
    ("Goleniów", "Goleniów"),
    ("Gorzów Śląski", "Gorzów Śląski"),
    ("Góra", "Góra"),
    ("Golina", "Golina"),
    ("Gorzów Wielkopolski", "Gorzów Wielkopolski"),
    ("Góra Kalwaria", "Góra Kalwaria"),
    ("Gołańcz", "Gołańcz"),
    ("Gostynin", "Gostynin"),
    ("Górzno", "Górzno"),
    ("Gołdap", "Gołdap"),
    ("Grabów nad Prosną", "Grabów nad Prosną"),
    ("Grodzisk Wielkopolski", "Grodzisk Wielkopolski"),
    ("Gryfice", "Gryfice"),
    ("Grajewo", "Grajewo"),
    ("Grójec", "Grójec"),
    ("Gryfino", "Gryfino"),
    ("Grodków", "Grodków"),
    ("Grudziądz", "Grudziądz"),
    ("Gryfów Śląski", "Gryfów Śląski"),
    ("Grodzisk Mazowiecki", "Grodzisk Mazowiecki"),
    ("Grybów", "Grybów"),
    ("Gubin", "Gubin"),
    ("Hajnówka", "Hajnówka"),
    ("Halinów", "Halinów"),
    ("Hel", "Hel"),
    ("Hrubieszów", "Hrubieszów"),
    ("Iława", "Iława"),
    ("Inowrocław", "Inowrocław"),
    ("Iłowa", "Iłowa"),
    ("Ińsko", "Ińsko"),
    ("Iłża", "Iłża"),
    ("Iwonicz Zdrój", "Iwonicz Zdrój"),
    ("Imielin", "Imielin"),
    ("Izbica Kujawska", "Izbica Kujawska"),
    ("Jabłonowo Pomorskie", "Jabłonowo Pomorskie"),
    ("Jastrowie", "Jastrowie"),
    ("Jelcz-Laskowice", "Jelcz-Laskowice"),
    ("Janikowo", "Janikowo"),
    ("Jastrzębie Zdrój", "Jastrzębie Zdrój"),
    ("Jelenia Góra", "Jelenia Góra"),
    ("Janowiec Wielkopolski", "Janowiec Wielkopolski"),
    ("Jawor", "Jawor"),
    ("Jeziorany", "Jeziorany"),
    ("Janów Lubelski", "Janów Lubelski"),
    ("Jaworzno", "Jaworzno"),
    ("Jędrzejów", "Jędrzejów"),
    ("Jaraczewo", "Jaraczewo"),
    ("Jaworzyna Śląska", "Jaworzyna Śląska"),
    ("Jordanów", "Jordanów"),
    ("Jarocin", "Jarocin"),
    ("Jedlicze", "Jedlicze"),
    ("Józefów", "Józefów"),
    ("Jarosław", "Jarosław"),
    ("Jedlina Zdrój", "Jedlina Zdrój"),
    ("Józefów (Biłgoraj County)", "Józefów (Biłgoraj County)"),
    ("Jasień", "Jasień"),
    ("Jedwabne", "Jedwabne"),
    ("Józefów nad Wisłą", "Józefów nad Wisłą"),
    ("Jasło", "Jasło"),
    ("Jutrosin", "Jutrosin"),
    ("Jastarnia", "Jastarnia"),
    ("Kalety", "Kalety"),
    ("Kamień Pomorski", "Kamień Pomorski"),
    ("Kartuzy", "Kartuzy"),
    ("Kalisz", "Kalisz"),
    ("Kamieńsk", "Kamieńsk"),
    ("Katowice", "Katowice"),
    ("Kalisz Pomorski", "Kalisz Pomorski"),
    ("Kańczuga", "Kańczuga"),
    ("Kazimierz Dolny", "Kazimierz Dolny"),
    ("Kalwaria Zebrzydowska", "Kalwaria Zebrzydowska"),
    ("Karczew", "Karczew"),
    ("Kazimierza Wielka", "Kazimierza Wielka"),
    ("Kałuszyn", "Kałuszyn"),
    ("Kargowa", "Kargowa"),
    ("Kąty Wrocławskie", "Kąty Wrocławskie"),
    ("Kamienna Góra", "Kamienna Góra"),
    ("Karlino", "Karlino"),
    ("Kcynia", "Kcynia"),
    ("Kamień Krajeński", "Kamień Krajeński"),
    ("Karpacz", "Karpacz"),
    ("Kędzierzyn-Koźle", "Kędzierzyn-Koźle"),
    ("Kietrz", "Kietrz"),
    ("Kłobuck", "Kłobuck"),
    ("Kępice", "Kępice"),
    ("Kisielice", "Kisielice"),
    ("Kłodawa", "Kłodawa"),
    ("Kępno", "Kępno"),
    ("Kleczew", "Kleczew"),
    ("Kłodzko", "Kłodzko"),
    ("Kętrzyn", "Kętrzyn"),
    ("Kleszczele", "Kleszczele"),
    ("Knurów", "Knurów"),
    ("Kęty", "Kęty"),
    ("Kluczbork", "Kluczbork"),
    ("Knyszyn", "Knyszyn"),
    ("Kielce", "Kielce"),
    ("Kłecko", "Kłecko"),
    ("Kobylin", "Kobylin"),
    ("Konin", "Konin"),
    ("Koszalin", "Koszalin"),
    ("Kobyłka", "Kobyłka"),
    ("Konstancin-Jeziorna", "Konstancin-Jeziorna"),
    ("Kościan", "Kościan"),
    ("Kock", "Kock"),
    ("Konstantynów Łódzki", "Konstantynów Łódzki"),
    ("Kościerzyna", "Kościerzyna"),
    ("Kolbuszowa", "Kolbuszowa"),
    ("Końskie", "Końskie"),
    ("Kowal", "Kowal"),
    ("Kolno", "Kolno"),
    ("Koprzywnica", "Koprzywnica"),
    ("Kowalewo Pomorskie", "Kowalewo Pomorskie"),
    ("Kolonowskie", "Kolonowskie"),
    ("Korfantów", "Korfantów"),
    ("Kowary", "Kowary"),
    ("Koło", "Koło"),
    ("Koziegłowy", "Koziegłowy"),
    ("Kraśnik", "Kraśnik"),
    ("Krasnystaw", "Krasnystaw"),
    ("Krosno", "Krosno"),
    ("Krasnobród", "Krasnobród"),
    ("Krosno Odrzańskie", "Krosno Odrzańskie"),
    ("Krupe", "Krupe"),
    ("Krotoszyn", "Krotoszyn"),
    ("Krzemienica", "Krzemienica"),
    ("Kruszwica", "Kruszwica"),
    ("Kruszyn", "Kruszyn"),
    ("Krynki", "Krynki"),
    ("Krzemionki", "Krzemionki"),
    ("Kruszyna", "Kruszyna"),
    ("Krynice", "Krynice"),
    ("Krzyż Wielkopolski", "Krzyż Wielkopolski"),
    ("Kwidzyn", "Kwidzyn"),
    ("Lądek-Zdrój", "Lądek-Zdrój"),
    ("Laskowa", "Laskowa"),
    ("Leba", "Leba"),
    ("Lębork", "Lębork"),
    ("Lublin", "Lublin"),
    ("Lubartów", "Lubartów"),
    ("Lubań", "Lubań"),
    ("Lubin", "Lubin"),
    ("Lubiniec", "Lubiniec"),
    ("Lutowiska", "Lutowiska"),
    ("Lwówek Śląski", "Lwówek Śląski"),
    ("Łapy", "Łapy"),
    ("Łask", "Łask"),
    ("Łęczna", "Łęczna"),
    ("Łomża", "Łomża"),
    ("Łowicz", "Łowicz"),
    ("Łódź", "Łódź"),
    ("Łuków", "Łuków"),
    ("Łuków (Rawski County)", "Łuków (Rawski County)"),
    ("Miejska Górka", "Miejska Górka"),
    ("Mielec", "Mielec"),
    ("Mikołów", "Mikołów"),
    ("Miejsce Piastowe", "Miejsce Piastowe"),
    ("Międzyrzec Podlaski", "Międzyrzec Podlaski"),
    ("Mogilno", "Mogilno"),
    ("Miechów", "Miechów"),
    ("Międzychód", "Międzychód"),
    ("Mońki", "Mońki"),
    ("Milanówek", "Milanówek"),
    ("Mława", "Mława"),
    ("Morąg", "Morąg"),
    ("Milicz", "Milicz"),
    ("Młynary", "Młynary"),
    ("Mrągowo", "Mrągowo"),
    ("Miłakowo", "Miłakowo"),
    ("Mściwojów", "Mściwojów"),
    ("Miłomłyn", "Miłomłyn"),
    ("Mińsk Mazowiecki", "Mińsk Mazowiecki"),
    ("Mysłowice", "Mysłowice"),
    ("Nadziejewo", "Nadziejewo"),
    ("Nowe Miasteczko", "Nowe Miasteczko"),
    ("Nowa Ruda", "Nowa Ruda"),
    ("Nidzica", "Nidzica"),
    ("Nowe Miasto Lubawskie", "Nowe Miasto Lubawskie"),
    ("Nowa Sól", "Nowa Sól"),
    ("Niegowa", "Niegowa"),
    ("Nowe Skalmierzyce", "Nowe Skalmierzyce"),
    ("Nowogard", "Nowogard"),
    ("Niemodlin", "Niemodlin"),
    ("Nowy Dwór Mazowiecki", "Nowy Dwór Mazowiecki"),
    ("Nowy Targ", "Nowy Targ"),
    ("Nisko", "Nisko"),
    ("Nowy Dwór Gdański", "Nowy Dwór Gdański"),
    ("Nowy Wiśnicz", "Nowy Wiśnicz"),
    ("Niwki", "Niwki"),
    ("Nysa", "Nysa"),
    ("Nowa Dęba", "Nowa Dęba"),
    ("Oborniki", "Oborniki"),
    ("Olsztyn", "Olsztyn"),
    ("Oleśnica", "Oleśnica"),
    ("Oborniki Śląskie", "Oborniki Śląskie"),
    ("Olechów", "Olechów"),
    ("Oławka", "Oławka"),
    ("Ostróda", "Ostróda"),
    ("Ostrów Mazowiecka", "Ostrów Mazowiecka"),
    ("Ostrowiec Świętokrzyski", "Ostrowiec Świętokrzyski"),
    ("Ostrów Wielkopolski", "Ostrów Wielkopolski"),
    ("Ostrzeszów", "Ostrzeszów"),
    ("Ostrołęka", "Ostrołęka"),
    ("Pabianice", "Pabianice"),
    ("Płock", "Płock"),
    ("Polanica-Zdrój", "Polanica-Zdrój"),
    ("Poznań", "Poznań"),
    ("Pakość", "Pakość"),
    ("Pruszcz Gdański", "Pruszcz Gdański"),
    ("Pruszków", "Pruszków"),
    ("Paniec", "Paniec"),
    ("Przemyśl", "Przemyśl"),
    ("Przygodzice", "Przygodzice"),
    ("Puławy", "Puławy"),
    ("Puszczykowo", "Puszczykowo"),
    ("Piaseczno", "Piaseczno"),
    ("Pyrzyce", "Pyrzyce"),
    ("Radom", "Radom"),
    ("Racibórz", "Racibórz"),
    ("Rawa Mazowiecka", "Rawa Mazowiecka"),
    ("Radomsko", "Radomsko"),
    ("Radzionków", "Radzionków"),
    ("Rybnik", "Rybnik"),
    ("Rymanów", "Rymanów"),
    ("Rzepin", "Rzepin"),
    ("Ryki", "Ryki"),
    ("Rzeszów", "Rzeszów"),
    ("Sanok", "Sanok"),
    ("Sandomierz", "Sandomierz"),
    ("Sieradz", "Sieradz"),
    ("Sierpc", "Sierpc"),
    ("Siedlce", "Siedlce"),
    ("Słupca", "Słupca"),
    ("Słupsk", "Słupsk"),
    ("Tarnobrzeg", "Tarnobrzeg"),
    ("Tarnów", "Tarnów"),
    ("Tuchola", "Tuchola"),
    ("Tarnowskie Góry", "Tarnowskie Góry"),
    ("Tuchów", "Tuchów"),
    ("Turawa", "Turawa"),
    ("Tomaszów Lubelski", "Tomaszów Lubelski"),
    ("Turek", "Turek"),
    ("Tłuszcz", "Tłuszcz"),
    ("Tuczyn", "Tuczyn"),
    ("Tychy", "Tychy"),
    ("Ustroń", "Ustroń"),
    ("Ustrzyki Dolne", "Ustrzyki Dolne"),
    ("Ustronie Morskie", "Ustronie Morskie"),
    ("Wadowice", "Wadowice"),
    ("Wałbrzych", "Wałbrzych"),
    ("Wałcz", "Wałcz"),
    ("Warka", "Warka"),
    ("Włocławek", "Włocławek"),
    ("Włoszczowa", "Włoszczowa"),
    ("Warszawa", "Warszawa"),
    ("Włodawa", "Włodawa"),
    ("Wieliczka", "Wieliczka"),
    ("Wysokie Mazowieckie", "Wysokie Mazowieckie"),
    ("Wyszków", "Wyszków"),
    ("Wojnicz", "Wojnicz"),
    ("Wronki", "Wronki"),
    ("Wrocław", "Wrocław"),
    ("Września", "Września"),
    ("Zabrze", "Zabrze"),
    ("Zamość", "Zamość"),
    ("Zakopane", "Zakopane"),
    ("Zarzecze", "Zarzecze"),
    ("Złocieniec", "Złocieniec"),
    ("Złotów", "Złotów"),
    ("Zielona Góra", "Zielona Góra"),
    ("Żary", "Żary"),
    ("Żelechów", "Żelechów"),
    ("Żagań", "Żagań"),
    ("Żary", "Żary")
)




#
# locations = [
#     "Aleksandrów Kujawski", "Andrychów", "Aleksandrów Łódzki", "Annopol", "Alwernia", "Augustów",
#     "Babimost", "Barczewo", "Barwice", "Baborów", "Bardo", "Bełchatów", "Baranów Sandomierski", "Barlinek", "Bełżyce",
#     "Barcin", "Bartoszyce", "Będzin", "Biała", "Biecz", "Bieżuń", "Biała Piska", "Bielawa", "Biłgoraj",
#     "Biała Podlaska", "Bielsk Podlaski", "Biskupiec", "Biała Rawska", "Bielsko-Biała", "Bisztynek", "Białobrzegi", "Bieruń",
#     "Blachownia", "Białogard", "Bierutów", "Błaszki", "Biały Bór", "Błażowa", "Białystok", "Błonie", "Bobolice",
#     "Bolków", "Brzeg", "Bobowa", "Borek Wielkopolski", "Brzeg Dolny", "Bochnia", "Borne Sulinowo", "Brzesko",
#     "Bodzentyn", "Braniewo", "Brzeszcze", "Bogatynia", "Brańsk", "Brześć Kujawski", "Boguchwała", "Brodnica", "Brzeziny",
#     "Boguszów-Gorce", "Brok", "Brzostek", "Bojanowo", "Brusy", "Brzozów", "Bolesławiec", "Brwinów",
#     "Buk", "Bydgoszcz", "Bukowno", "Bystrzyca Kłodzka", "Busko Zdrój", "Bytom", "Bychawa", "Bytom Odrzański", "Byczyna",
#     "Bytów", "Cedynia", "Chocianów", "Chojnów", "Chełm", "Chociwel", "Choroszcz", "Chełmek", "Chocz", "Chorzele",
#     "Chełmno", "Chodecz", "Chorzów", "Chełmża", "Chodzież", "Choszczno", "Chęciny", "Chojna", "Chrzanów", "Chmielnik",
#     "Chojnice", "Ciechanowiec", "Czarna Białostocka", "Czerniejewo", "Ciechanów", "Czarna Woda", "Czersk", "Ciechocinek",
#     "Czarne", "Czerwieńsk", "Cieszanów", "Czarnków", "Czerwionka-Leszczyny", "Cieszyn", "Czchów", "Częstochowa",
#     "Ciężkowice", "Czechowice-Dziedzice", "Człopa", "Cybinka", "Czeladź", "Człuchów", "Czaplinek", "Czempiń", "Czyżew",
#     "Daleszyce", "Debrzno", "Dobra (Turek County)", "Darłowo", "Dębica", "Dobre Miasto", "Dąbie", "Dęblin", "Dobrodzień",
#     "Dąbrowa Białostocka", "Dębno", "Dobrzany", "Dąbrowa Górnicza", "Dobczyce", "Dobrzyca", "Dąbrowa Tarnowska", "Dobiegniew",
#     "Dobrzyń nad Wisłą", "Dąbrowa Tarnowska", "Dobra (Łobez County)", "Dolsk", "Drawno", "Drzewica", "Działoszyce",
#     "Drawsko Pomorskie", "Dukla", "Działoszyn", "Drezdenko", "Duszniki Zdrój", "Dzierzgoń", "Drobin", "Dynów", "Dzierżoniów",
#     "Drohiczyn", "Działdowo", "Dziwnów", "Elbląg", "Ełk", "Frampol", "Frombork", "Garwolin", "Gliwice", "Głuchołazy",
#     "Gąbin", "Głogów", "Głuszyca", "Gdańsk", "Głogów Małopolski", "Gniew", "Gdynia", "Głogówek", "Gniewkowo", "Giżycko",
#     "Głowno", "Gniezno", "Glinojeck", "Głubczyce", "Gniewkowo", "Gogolin", "Goniądz", "Gostyń", "Golczewo", "Gorlice",
#     "Gozdnica", "Goleniów", "Gorzów Śląski", "Góra", "Golina", "Gorzów Wielkopolski", "Góra Kalwaria", "Gołańcz",
#     "Gostynin", "Górzno", "Gołdap", "Grabów nad Prosną", "Grodzisk Wielkopolski", "Gryfice", "Grajewo", "Grójec",
#     "Gryfino", "Grodków", "Grudziądz", "Gryfów Śląski", "Grodzisk Mazowiecki", "Grybów", "Gubin", "Hajnówka",
#     "Halinów", "Hel", "Hrubieszów", "Iława", "Inowrocław", "Iłowa", "Ińsko", "Iłża", "Iwonicz Zdrój", "Imielin",
#     "Izbica Kujawska", "Jabłonowo Pomorskie", "Jastrowie", "Jelcz-Laskowice", "Janikowo", "Jastrzębie Zdrój", "Jelenia Góra",
#     "Janowiec Wielkopolski", "Jawor", "Jeziorany", "Janów Lubelski", "Jaworzno", "Jędrzejów", "Jaraczewo", "Jaworzyna Śląska",
#     "Jordanów", "Jarocin", "Jedlicze", "Józefów", "Jarosław", "Jedlina Zdrój", "Józefów (Biłgoraj County)", "Jasień",
#     "Jedwabne", "Józefów nad Wisłą", "Jasło", "Jutrosin", "Jastarnia", "Kalety", "Kamień Pomorski", "Kartuzy", "Kalisz",
#     "Kamieńsk", "Katowice", "Kalisz Pomorski", "Kańczuga", "Kazimierz Dolny", "Kalwaria Zebrzydowska", "Karczew",
#     "Kazimierza Wielka", "Kałuszyn", "Kargowa", "Kąty Wrocławskie", "Kamienna Góra", "Karlino", "Kcynia", "Kamień Krajeński",
#     "Karpacz", "Kędzierzyn-Koźle", "Kietrz", "Kłobuck", "Kępice", "Kisielice", "Kłodawa", "Kępno", "Kleczew", "Kłodzko",
#     "Kętrzyn", "Kleszczele", "Knurów", "Kęty", "Kluczbork", "Knyszyn", "Kielce", "Kłecko", "Kobylin", "Konin", "Koszalin",
#     "Kobyłka", "Konstancin-Jeziorna", "Kościan", "Kock", "Konstantynów Łódzki", "Kościerzyna", "Kolbuszowa", "Końskie",
#     "Kowal", "Kolno", "Koprzywnica", "Kowalewo Pomorskie", "Kolonowskie", "Korfantów", "Kowary", "Koło", "Koziegłowy",
#     "Kraśnik", "Krasnystaw", "Krosno", "Krasnobród", "Krosno Odrzańskie", "Krupe", "Krotoszyn", "Krzemienica", "Kruszwica",
#     "Kruszyn", "Krynki", "Krzemionki", "Kruszyna", "Krynice", "Krzyż Wielkopolski", "Kwidzyn", "Kalisz", "Karpacz", "Kęty",
#     "Lądek-Zdrój", "Laskowa", "Leba", "Lębork", "Lublin", "Lubartów", "Lubań", "Lubartów", "Lubliniec", "Lubin", "Lubartów",
#     "Lubiniec", "Lutowiska", "Lwówek Śląski", "Lwówek", "Łapy", "Łask", "Łęczna", "Łomża", "Łowicz", "Łódź", "Łuków",
#     "Łuków (Rawski County)", "Miejska Górka", "Mielec", "Mikołów", "Miejsce Piastowe", "Międzyrzec Podlaski", "Mogilno",
#     "Miechów", "Międzychód", "Mońki", "Milanówek", "Mława", "Morąg", "Milicz", "Młynary", "Mrągowo", "Miłakowo",
#     "Mogilno", "Mściwojów", "Miłomłyn", "Morąg", "Mińsk Mazowiecki", "Mysłowice", "Nadziejewo", "Nowe Miasteczko",
#     "Nowa Ruda", "Nidzica", "Nowe Miasto Lubawskie", "Nowa Sól", "Niegowa", "Nowe Skalmierzyce", "Nowogard", "Niemodlin",
#     "Nowy Dwór Mazowiecki", "Nowy Targ", "Nisko", "Nowy Dwór Gdański", "Nowy Wiśnicz", "Niwki", "Nysa", "Nyski",
#     "Nowa Dęba", "Oborniki", "Olsztyn", "Oleśnica", "Oborniki Śląskie", "Olsztyn (Mazury)", "Olechów", "Oławka", "Olechów",
#     "Ostróda", "Ostrów Mazowiecka", "Ostrowiec Świętokrzyski", "Ostrów Wielkopolski", "Ostróda", "Ostrzeszów", "Ostrołęka",
#     "Pabianice", "Płock", "Polanica-Zdrój", "Poznań", "Pakość", "Pruszcz Gdański", "Pruszków", "Paniec", "Przemyśl",
#     "Przygodzice", "Puławy", "Puszczykowo", "Piaseczno", "Pyrzyce", "Radom", "Racibórz", "Rawa Mazowiecka", "Radomsko",
#     "Radzionków", "Rawa Mazowiecka", "Rybnik", "Rymanów", "Rzepin", "Ryki", "Rzeszów", "Sanok", "Sandomierz", "Sieradz",
#     "Sierpc", "Siedlce", "Słupca", "Słupsk", "Tarnobrzeg", "Tarnów", "Tuchola", "Tarnowskie Góry", "Tuchów", "Turawa",
#     "Tomaszów Lubelski", "Turek", "Tłuszcz", "Tuczyn", "Tychy", "Ustroń", "Ustrzyki Dolne", "Ustronie Morskie",
#     "Wadowice", "Wałbrzych", "Wałcz", "Warka", "Włocławek", "Włoszczowa", "Warszawa", "Włocławek", "Włodawa", "Wieliczka",
#     "Włoszczowa", "Włocławek", "Wysokie Mazowieckie", "Wyszków", "Wojnicz", "Wronki", "Wrocław", "Września", "Zabrze",
#     "Zamość", "Zakopane", "Zarzecze", "Złocieniec", "Złotów", "Zielona Góra", "Żary", "Żelechów", "Żagań", "Żary"
# ]
