# Generated by Django 5.1 on 2024-11-14 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communities", "0002_building_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField()),
                (
                    "place",
                    models.CharField(
                        choices=[("Część wspólna", "Common Area"), ("Mieszkanie", "Apartment"), ("Garaż", "Garage")]
                    ),
                ),
                ("severity", models.CharField(choices=[("Niska", "Low"), ("Średnia", "Medium"), ("Wysoka", "High")])),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Otwarta", "Open"),
                            ("W trakcie", "In Progress"),
                            ("Rozwiązana", "Resolved"),
                            ("Zamknięta", "Closed"),
                        ]
                    ),
                ),
                ("date_reported", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_resolved", models.DateTimeField(blank=True, null=True)),
                ("update_info", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="communities.building"
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
