# Generated by Django 5.1 on 2024-11-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/issues/<id:pk>"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="place",
            field=models.CharField(
                choices=[("Common Area", "Common Area"), ("Apartment", "Apartment"), ("Garage", "Garage")]
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="severity",
            field=models.CharField(choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")]),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In progress", "In progress"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                ]
            ),
        ),
    ]
