# Generated by Django 5.1 on 2024-11-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_remove_issue_update_info_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(blank=True, choices=[("Open", "Open"), ("Closed", "Closed")], null=True),
        ),
    ]
