# Generated by Django 5.1 on 2024-12-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_alter_issue_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="assigned_to",
        ),
    ]
