# Generated by Django 5.1 on 2024-11-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_building_manager"),
        ("invitations", "0004_auto_20230328_1430"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="communities.building",
            ),
        ),
        migrations.CreateModel(
            name="CustomInvitation",
            fields=[
                (
                    "invitation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="invitations.invitation",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Property Manager", "Group  Property Manager"),
                            ("Resident", "Group  Resident"),
                            ("Administrator", "Group  Administrator"),
                        ]
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="communities.building"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("invitations.invitation",),
        ),
    ]
