# Generated by Django 5.0.7 on 2024-08-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
        ("invitations", "0004_auto_20230328_1430"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomInvitation",
            fields=[
                (
                    "invitation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="invitations.invitation",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="communities.building"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("invitations.invitation",),
        ),
    ]
