# Generated by Django 5.0.7 on 2024-08-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
        ("users", "0002_custominvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="communities.building",
            ),
        ),
    ]
