# Generated by Django 5.0.7 on 2024-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="custominvitation",
            name="group",
            field=models.CharField(
                choices=[
                    ("Property Manager", "Group  Property Manager"),
                    ("Resident", "Group  Resident"),
                    ("Administrator", "Group  Administrator"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
