# Generated by Django 5.0.7 on 2024-08-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0004_alter_building_manager"),
        ("users", "0004_custominvitation_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custominvitation",
            name="building",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="communities.building"),
            preserve_default=False,
        ),
    ]
