# Generated by Django 5.0.7 on 2024-08-15 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="manager_id",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Property Manager"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_building",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
